BLENDER="C:\Program Files\Blender Foundation\Blender 4.1\blender.exe"
DIST=../dist

all : \
    $(DIST)/interrogation.pnct \
    $(DIST)/interrogation.scene \

$(DIST)/interrogation.scene : interrogation.blend export-scene.py
	$(BLENDER) --background --python export-scene.py -- "interrogation.blend:Collection" "$(DIST)/interrogation.scene"

$(DIST)/interrogation.pnct : interrogation.blend export-meshes.py
	$(BLENDER) --background --python export-meshes.py -- "interrogation.blend:Collection" "$(DIST)/interrogation.pnct"